#!/bin/sh

case "$1" in
    start)
        echo "Iniciando busybox httpd..."
        /usr/sbin/httpd -h /var/www
        ;;
    stop)
        echo "Parando busybox httpd..."
        killall httpd
        ;;
    restart)
        echo "Reiniciando busybox httpd..."
        killall httpd
        /usr/sbin/httpd -h /var/www
        ;;
    *)
        echo "Uso: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
